### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by travelscope-21** [travelscope/travelscope#1]
# Sunday, 19 February 2023

- Figma URL: [TravelScope](https://www.figma.com/file/DntDIGr23JZzRjjBflxBLH/TravelScope?node-id=0%3A1&t=Amc7DBI9IXKCvhcs-0)
- Deployment: [TravelScope](https://travelscopee.netlify.app)

### Arif Setiawan
- [x] UI Design
- [x] Landing Page
   - [x] Navbar
   - [x] Home Section
            - Form Search
   - [x] About Us Section
   - [x] Explore Us
            - Card Travel Info (Muhammad Farkhan Syafi'i)
   - [x] Contact Us
            - Form Send
 
### Rofiq Ahmad
- [x] Setup Bitwarden
- [x] Add Destinations data
- [x] Deployment
- [x] About Us
- [x] Contact Us
- [x] Update README.md

### Muhammad Farkhan Syafi'i
- [x] Travel info page 
     - Title
     - Details
     - Price
     - Add Button
- [x] See More page for exploring 
- [x] Rest API

### Karim Hasibuan
- [x] Present
- [x] Setup image in ImageKit
